### ISSUE TITLE
Get-JamTreeSizeFree and Get-VideoLanVlcPlayer return Version as PSObject instead of System.String

### ISSUE THREAD

**Issue by msfreaks** [aaronparker/Evergreen#109] opened 2021-01-29 14:01 UTC
**Describe the bug**

**To Reproduce**
$evergreen = Get-JamTreeSizeFree
$evergreen.Version

4.42
$evergreen.Version | fl

4.42
$evergreen.Version | fl -force

PSPath       : C:\Users\amensc\AppData\Local\Temp\tmpB35D.tmp
PSParentPath : C:\Users\amensc\AppData\Local\Temp
PSChildName  : tmpB35D.tmp
PSDrive      : C
PSProvider   : Microsoft.PowerShell.Core\FileSystem
ReadCount    : 1
Length       : 4

**Expected behavior**
Expected to return a .Version attribute of type System.String

**Desktop (please complete the following information):**
 - OS: Win10 20H2 fully patched
 - Evergreen 2101.275

**Additional context**
I don't know if these are the only two functions behaving like this.

**Comment by aaronparker** [comment] 2021-01-30 09:16
In `Invoke-WebRequestWrapper` I have an option to use `-OutFile` when returning data from a URL. This has been required to format specific web request content correctly. This will be the cause of the version type on `Get-JamTreeSizeFree`.

There's a difference in what `Invoke-WebRequest` returns from `https://update.jam-software.de/functions/getCurrentVersion.php?article=80`, for example, with and without `-OutFile`.

I can likely filter what's returned for the version property before returning it to the pipeline; however, I should probably look into what the difference in the content returned is in the first place.

There are a number of functions that will be affected by this.

**Comment by aaronparker** [comment] 2021-01-30 09:56
Some apps return data from their update locations as `application/octet-stream`. I might be able to fix this with `Invoke-RestMethod` - this has worked for `Get-VideoLanVlcPlayer`

**Comment by msfreaks** [comment] 2021-01-30 11:45
Great!
Before investing a lot of time in this, I can also account for the difference in types in my scripts when I use Evergreen's functions.
So it's more of a 'nice to have' adjustment than a bug really.

**Comment by aaronparker** [comment] 2021-02-01 09:04
It's given me the opportunity to move a few functions to `Get-RestMethodWrapper` which simplifies these functions and should produce the right output format as a result.

**Comment by aaronparker** [comment] 2021-02-08 09:54
Fixed in c517a73a818fbf413875a1cdb8703ca1cce1c7eb

**Closed by aaronparker** 2021-02-08 09:54 UTC
Labels: bug
